"""Tests for the spec-C apiKeyHelper token helper generated by setup_claude.py.

The helper is emitted as a source string and written to
~/.claude/anthropic-token-helper.py; Claude Code runs it and reads stdout
verbatim as the bearer token. These tests extract that generated source,
exec it in a namespace with the SDK/env mocked, and assert:

  - SP branch mints via the SDK (Config.authenticate) and strips "Bearer "
    (the M2M profile is NOT usable via `databricks auth token`; C-O1 proved
    the SDK-minted token is accepted by /anthropic).
  - PAT fallback fires when no SP profile / SDK is available.
  - stdout carries the raw token only (no newline, no "Bearer ").
"""

import re
import types

import pytest
import token_helper


def _extract_helper_source() -> str:
    src = open("token_helper.py").read()
    m = re.search(r"_HELPER_SRC = '''(.*?)'''", src, re.DOTALL)
    assert m, "could not locate _HELPER_SRC literal in token_helper.py"
    return m.group(1)


def _load_helper_module():
    """exec the generated helper source into a fresh module namespace."""
    mod = types.ModuleType("generated_helper")
    exec(compile(_extract_helper_source(), "anthropic-token-helper.py", "exec"), mod.__dict__)
    return mod


class TestSpBranch:
    def test_runtime_resolver_prefers_loopback_broker(self, monkeypatch):
        monkeypatch.setenv("CODA_SP_TOKEN_BROKER_URL", "http://127.0.0.1:4010/token")
        monkeypatch.setattr(
            token_helper,
            "urlopen",
            lambda *_a, **_k: _BrokerResponse(b"broker-token"),
        )

        assert token_helper.resolve_sp_oauth_token() == "broker-token"

    def test_sdk_mint_strips_bearer_prefix(self, monkeypatch):
        """SP path returns the raw token with 'Bearer ' stripped."""
        mod = _load_helper_module()

        fake_cfg = types.SimpleNamespace(authenticate=lambda: {"Authorization": "Bearer sp-tok-123"})
        fake_core = types.ModuleType("databricks.sdk.core")
        fake_core.Config = lambda profile=None: fake_cfg
        monkeypatch.setitem(__import__("sys").modules, "databricks.sdk.core", fake_core)

        assert mod._sp_oauth_token() == "sp-tok-123"

    def test_sdk_missing_returns_none(self, monkeypatch):
        """No SDK importable -> SP branch yields None (caller falls back)."""
        mod = _load_helper_module()
        # Force the import inside _sp_oauth_token to fail.
        real_import = __builtins__["__import__"] if isinstance(__builtins__, dict) else __builtins__.__import__

        def boom(name, *a, **k):
            if name.startswith("databricks"):
                raise ImportError("no sdk")
            return real_import(name, *a, **k)

        monkeypatch.setattr("builtins.__import__", boom)
        assert mod._sp_oauth_token() is None

    def test_authenticate_raises_returns_none(self, monkeypatch):
        """Absent/invalid profile -> authenticate() raises -> None."""
        mod = _load_helper_module()

        def raising_config(profile=None):
            raise RuntimeError("profile not found")

        fake_core = types.ModuleType("databricks.sdk.core")
        fake_core.Config = raising_config
        monkeypatch.setitem(__import__("sys").modules, "databricks.sdk.core", fake_core)

        assert mod._sp_oauth_token() is None


class TestPatFallback:
    def test_env_token_preferred(self, monkeypatch):
        mod = _load_helper_module()
        monkeypatch.setenv("DATABRICKS_TOKEN", "dapi-env")
        assert mod._pat_token() == "dapi-env"

    def test_default_profile_token(self, tmp_path, monkeypatch):
        mod = _load_helper_module()
        monkeypatch.delenv("DATABRICKS_TOKEN", raising=False)
        cfg = tmp_path / ".databrickscfg"
        cfg.write_text("[DEFAULT]\nhost = h\ntoken = dapi-default\n")
        monkeypatch.setenv("HOME", str(tmp_path))
        assert mod._pat_token() == "dapi-default"


class TestMainOutput:
    def test_stdout_is_raw_token_no_newline(self, monkeypatch, capsys):
        """main() writes only the token — no trailing newline, no prefix."""
        mod = _load_helper_module()
        monkeypatch.setattr(mod, "_sp_oauth_token", lambda: "tok-abc")
        mod.main()
        out = capsys.readouterr().out
        assert out == "tok-abc"  # exact — no newline, no "Bearer "

    def test_sp_wins_over_pat(self, monkeypatch, capsys):
        mod = _load_helper_module()
        monkeypatch.setattr(mod, "_sp_oauth_token", lambda: "sp-wins")
        monkeypatch.setattr(mod, "_pat_token", lambda: "pat-loses")
        mod.main()
        assert capsys.readouterr().out == "sp-wins"

    def test_falls_back_to_pat(self, monkeypatch, capsys):
        mod = _load_helper_module()
        monkeypatch.setattr(mod, "_sp_oauth_token", lambda: None)
        monkeypatch.setattr(mod, "_pat_token", lambda: "pat-used")
        mod.main()
        assert capsys.readouterr().out == "pat-used"

    def test_no_source_exits_nonzero(self, monkeypatch):
        mod = _load_helper_module()
        monkeypatch.setattr(mod, "_sp_oauth_token", lambda: None)
        monkeypatch.setattr(mod, "_pat_token", lambda: None)
        with pytest.raises(SystemExit) as e:
            mod.main()
        assert e.value.code == 1


class _BrokerResponse:
    def __init__(self, body):
        self.body = body

    def __enter__(self):
        return self

    def __exit__(self, *_args):
        return None

    def read(self):
        return self.body
